services:
    backend:
        image: gw2tp-backend
        container_name: gw2tp-backend
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        depends_on:
            - mongodb

    frontend:
        image: gw2tp-frontend
        container_name: gw2tp-frontend
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "5000:5000"
        environment:
            - BACKEND_URL=http://backend:8000
    mongodb:
        image: mongo:7.0.12
        container_name: gw2tp-mongodb
        volumes:
            - mongodb-data:/data/db
        env_file:
            - ./mongodb/.env
        depends_on:
            - mongo-express

    mongo-express:
        image: mongo-express:1.0.2
        ports:
            - 8081:8081
        container_name: gw2tp-mongo-express
        env_file:
            - ./mongo-express/.env

volumes:
    mongodb-data:
